# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: rx-angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git fetch --no-tags --prune --depth=5 origin master

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      env:
        HUSKY_SKIP_INSTALL: 'true'
      run: yarn --frozen-lockfile --no-progress --non-interactive

    - run: yarn nx affected:lint --parallel --base=origin/master
    - run: yarn nx affected:test --parallel --base=origin/master
    - run: yarn nx affected:e2e --parallel --headless --base=origin/master
    # Do not run builds in parallel since it will cause `ngcc` compiler deadlocks.
    - run: yarn nx affected:build --with-deps --base=origin/master
